### ISSUE TITLE
create_proc_entry has been removed for Kernel 3.10 and above

### ISSUE THREAD

**Issue by Johnny-Ich** [dkorunic/uptime_hack#1]
'create_proc_entry' function is deprecated, it's replacement is 'proc_create'. 
You are using it in ‘proc_init’ at Line 154 of the file uptime_hack.c
Please can you fix it?

**Comment by herrsergio** [comment]
Yes please, can you fix it.

**Comment by parkour86** [comment]
Looks like it's fixed in this fork version:
https://github.com/mlnkrlc/uptime_hack

**Comment by Johnny-Ich** [comment]
@parkour86 Thanks for your reply. :)
